kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le

steps:
- name: build
  commands:
  - docker login -u $env:USERNAME -p $env:PASSWORD
  - docker build -f Dockerfile.linux.ppc64le -t drone/git:ppc64le .
  - docker tag drone/git:ppc64le sbm13/drone/git:ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push

