kind: pipeline
type: docker
name: linux-ppc64le

platform:
  arch: ppc64le
  os: linux

steps:
- name: build
  image: golang:1.10
  commands:
  - cd posix
  - tar -xf fixtures.tar -C /
  - go test -v

- name: publish
  image: plugins/docker:18
  settings:
    dockerfile: docker/Dockerfile.linux.ppc64le
    repo: drone/git
    auto_tag: "true"
    auto_tag_suffix: linux-ppc64le
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
