kind: pipeline
type: docker
name: linux-ppc64le

platform:
  arch: ppc64le
  os: linux

steps:
- name: build
  image: golang:1.10
  commands:
  - echo "It tested!"

- name: publish
  image: alpine
  settings:
    dockerfile: docker/Dockerfile.linux.ppc64le
    repo: sbm13/drone-git
    auto_tag: "true"
    auto_tag_suffix: linux-ppc64le
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
