kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le


 
steps:
- name: build
  image: quay.io/sumangalm/drone-git:linux-ppc64le
  command:
  
  - docker tag drone/git:ppc64le sbm13/drone/git:linux-ppc64le
  - docker push sbm13/drone/git:linux-ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push

