kind: pipeline
type: docker
name: linux-ppc64le

platform:
  arch: ppc64le
  os: linux

steps:
- name: build
  image: plugins/docker:18
  commands:
  - echo " Build successfully"  
  - docker build -f docker/Dockerfile.linux.ppc64le -t drone/git:linux.ppc64le .
  - docker push drone/git:linux.ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

trigger:
  event:
  - push

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: "true"
    ignore_missing: "true"
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - push
  - tag

depends_on:
- linux-ppc64le
