kind: pipeline
type: ssh
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le

server:
  host:
    from_secret: host
  password:
    from_secret: password
  user:
    from_secret: username
steps:
- name: build
  commands:
  
  - docker build -f drone-git:linux-ppc64le -f ./docker/Dockerfile.linux.ppc64le .
  - docker tag drone/git:ppc64le sbm13/drone/git:ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push

