kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le
steps:
- name: build
  image: golang:1.10
  commands:
  - cd posix
  - tar -xf fixtures.tar -C /
  - go test -v
  
- name: publish
  image: ppc64le/docker
  settings:
    dockerfile: docker/Dockerfile.linux.ppc64le
    repo: sbm13/drone
    auto_tag: "true"
    auto_tag_suffix: linux-ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push
  - tag
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: ppc64le/manifest
  settings:
    auto_tag: "true"
    ignore_missing: "true"
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - push
  - tag

depends_on:
- linux-ppc64le
