kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le
steps:
- name: build
  image: ppc64le/docker
  settings:
    dockerfile: docker/Dockerfile.linux.ppc64le
    repo: test/images
    auto_tag: "true"
    auto_tag_suffix: linux-ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push

