kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le

steps:
- name: build
  image: alpine
 
  environment:
   GOARCH: ppc64le
   GOOS: linux

- name: publish
  image: drone-runner
  settings:
    auto_tag: true
    auto_tag_suffix: linux-ppc64le
    dockerfile: docker/Dockerfile.server.linux.ppc64le
trigger:
  event:
  - push

