kind: pipeline
type: docker
name: linux-ppc64le

platform:
  os: linux
  arch: ppc64le

steps:
- name: build
  image: alpine
  commands:
  - echo " Build successfully"  
  - ls -la
  - ls -la Dockerfile
  - docker build -f docker/Dockerfile.linux.ppc64le -t drone/git:linux.ppc64le .
  - docker push drone/git:linux.ppc64le
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

trigger:
  event:
  - push

