kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: ppc64le
steps:
- name: clone
  commands: 
  - git clone https://github.com/sumangalm-1/test-images.git
  - cd test-images/
  - sh setup.sh
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
trigger:
  event:
  - push

